root - ERROR - Division por 0
root - ERROR - Division po 0
Traceback (most recent call last):
  File "/workspaces/cursoPyhon/Logs/try_log.py", line 7, in <module>
    division = 2/0
               ~^~
ZeroDivisionError: division by zero
